variables:
    TZ: "America/New_York"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    APT_CACHE_DIR: "$CI_PROJECT_DIR/apt-cache"
    POSTGRES_DB: custom_db
    POSTGRES_USER: custom_user
    POSTGRES_PASSWORD: custom_pass
    FARADAY_USER: custom_user
    FARADAY_PASSWORD: custom_pass
    FARADAY_EMAIL: test@test.com
    FARADAY_REF: white/dev
    EXECUTOR_DIR: ./basic_executor.py

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache/pip"
    - "$CI_PROJECT_DIR/apt-cache"


before_script:
    - mkdir -pv $APT_CACHE_DIR

stages:
    - testing
    - post_testing
    - integration-build
    - integration-test
    - build
    - publish
    - deploy

services:
    - postgres:latest


include:
  - local: .gitlab/ci/.pre-gitlab-ci.yml

  - local: .gitlab/ci/testing/.testing-gitlab-ci.yml

  - local: .gitlab/ci/publish/.pypi-gitlab-ci.yml
