
flake8:
    image: python:3
    stage: .pre
    script:
      - pip install flake8
      - flake8 .
    tags:
        - faradaytests


black:
    image: python:3
    stage: .pre
    script:
      - pip install black
      - black --line-length=119 --check .
    tags:
        - faradaytests
